### PR TITLE
Use gopkg.in/fsnotify.v0

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by omeid** [comment]
What is the advantage of this over the `x/fsnotify`? Specially when the `v0` the doc says

>This branch contains fsnotify.v0 which is API-compatible with howeyc/fsnotify. Bugfixes *may* be backported, but I recommend upgrading. 

So perhaps `gopkg.in/fsnotify.v1` would better?

**Comment by mattn** [comment]
I could not go get this in few hours ago.

On 2/21/15, omeid <notifications@github.com> wrote:
> What is the advantage of this over the `x/fsnotify`? Specially when the `v0`
> the doc says
>
>>This branch contains fsnotify.v0 which is API-compatible with
>> howeyc/fsnotify. Bugfixes *may* be backported, but I recommend upgrading.
>>
>
> So perhaps `gopkg.in/fsnotify.v1` would better?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/slurp-contrib/watch/pull/1#issuecomment-75355143


-- 
- Yasuhiro Matsumoto

**Comment by omeid** [comment]
I am sorry but I am not sure what you couldn't `go get` `gopkg.in/fsnotify.v1` or `golang.org/x/exp/fsnotify`?

**Comment by mattn** [comment]
`golang.org/x/exp/fsnotify` should be fail. also now.

**Comment by omeid** [comment]
Merged. Thanks.

**Pull request merged**
